/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import Clases.Controlador;
import Clases.Conexion;
/**
 *
 * @author YayiLeno
 */
public class frmLogeo extends javax.swing.JFrame {
    Conexion obj_conexion = new Conexion();
    Controlador obj_controlador = new Controlador();
    
    /**
     * Creates new form frmLogeo
     */
    public frmLogeo() {
        initComponents();
        setSize(512, 502);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Login");
        setVisible(true);
    }
    public void logeo() {
        try {
            String usuario = txtUsuario.getText();
            char[] passwordArreglo = passClave.getPassword();
            String clave = new String(passwordArreglo);

            String sql_consulta = "SELECT * FROM usuario WHERE Nombre_Usuario=? AND Clave_Usuario=?";
            PreparedStatement datos = obj_conexion.establecer_conexion().prepareStatement(sql_consulta);
            datos.setString(1, usuario);
            datos.setString(2, clave);
            obj_controlador.resultado = datos.executeQuery();

            if (obj_controlador.resultado.next()) {
                this.setVisible(false);
                frmInicio obj_inicio = new frmInicio();
                obj_inicio.setVisible(true);
                obj_inicio.lblUsuario.setText("Bienvenido, " + obj_controlador.resultado.getString("Tipo_Usuario"));

                if (obj_controlador.resultado.getString("Tipo_Usuario").equals("Usuario")) {
                    
                    if (obj_controlador.resultado.getString("Tipo_Usuario").equals("UsuarioGeneral")) {
                            
                        if(obj_controlador.resultado.getString("Tipo_Usuario").equals("SuperUsuario")) {
                            
                            if(obj_controlador.resultado.getString("Tipo_Usuario").equals("Administrador")) {
                                
                            }
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuario/Contraseña no Registrado o Inconrrecto", "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogeo = new javax.swing.JPanel();
        pnlIinicio = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblClave = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        passClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogeo.setBackground(new java.awt.Color(153, 153, 153));
        pnlLogeo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlIinicio.setBackground(new java.awt.Color(51, 51, 51));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 255, 255));
        lblTitulo.setText("Inicio de Seción");

        javax.swing.GroupLayout pnlIinicioLayout = new javax.swing.GroupLayout(pnlIinicio);
        pnlIinicio.setLayout(pnlIinicioLayout);
        pnlIinicioLayout.setHorizontalGroup(
            pnlIinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIinicioLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        pnlIinicioLayout.setVerticalGroup(
            pnlIinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIinicioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlLogeo.add(pnlIinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 100));

        btnLogin.setBackground(new java.awt.Color(0, 204, 204));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogeo.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 120, 40));

        lblClave.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblClave.setForeground(new java.awt.Color(0, 255, 255));
        lblClave.setText("Contraseña");
        pnlLogeo.add(lblClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 255, 255));
        lblUsuario.setText("Usuario");
        pnlLogeo.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(51, 51, 51));
        txtUsuario.setForeground(new java.awt.Color(0, 255, 255));
        pnlLogeo.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 330, 30));

        passClave.setBackground(new java.awt.Color(51, 51, 51));
        passClave.setForeground(new java.awt.Color(0, 255, 255));
        pnlLogeo.add(passClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 330, 30));

        getContentPane().add(pnlLogeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        logeo();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogeo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField passClave;
    private javax.swing.JPanel pnlIinicio;
    private javax.swing.JPanel pnlLogeo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
