package Interfaz;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import Clases.Conexion;
import Clases.Controlador;

public class frmLogin extends javax.swing.JFrame {
    Conexion obj_conexion = new Conexion();
    Controlador obj_controlador = new Controlador();
    
    public frmLogin() {
        initComponents();
        setSize(512, 502);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Login");
        setVisible(true);
    }

    public void logeo() {
        try {
            String usuario = txtUsuario.getText();
            char[] passwordArreglo = pwdClave.getPassword();
            String clave = new String(passwordArreglo);

            String sql_consulta = "SELECT * FROM Usuarios WHERE Nombre_Usuario=? AND Contraseña=?";
            PreparedStatement datos = obj_conexion.establecer_conexion().prepareStatement(sql_consulta);
            datos.setString(1, usuario);
            datos.setString(2, clave);
            obj_controlador.resultado = datos.executeQuery();

            if (obj_controlador.resultado.next()) {
                this.setVisible(false);
                frmInicio obj_inicio = new frmInicio();
                obj_inicio.setVisible(true);
                obj_inicio.lblUsuario.setText("Bienvenido, " + obj_controlador.resultado.getString("Nombre_Usuario"));

                //Si el resultado es un tipo de usuario como Usuario, se bloquearan ciertas funciones
                if (obj_controlador.resultado.getString("Tipo_Usuario").equals("Usuario")) {
                    obj_libros.btnEliminar.setEnabled(false);
                    obj_libros.btnModificar.setEnabled(false);
                    obj_libros.btnGuardar.setEnabled(false);
                    obj_libros.tblListado.setEnabled(false);
                    obj_libros.srcListado.setEnabled(false);
                    obj_libros.btnLimpiar.setEnabled(true);
                    obj_libros.btnBuscar.setEnabled(true);

                    //Si el resutlado es un tipo de usuario como SuperUsuario, se habilitaran todas las funciones    
                    if (obj_controlador.resultado.getString("Tipo_Usuario").equals("SuperUsuario")) {
                        obj_libros.btnEliminar.setEnabled(true);
                        obj_libros.btnModificar.setEnabled(true);
                        obj_libros.btnGuardar.setEnabled(true);
                        obj_libros.tblListado.setEnabled(true);
                        obj_libros.srcListado.setEnabled(true);
                        obj_libros.btnLimpiar.setEnabled(true);
                        obj_libros.btnBuscar.setEnabled(true);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contrasena incorrectos");
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        btnLogeo = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        pwdClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLogin.setBackground(new java.awt.Color(204, 204, 204));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicio.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(0, 204, 204));
        lblInicio.setText("Inicio de Sesion");
        jPanel1.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 24, -1, -1));

        pnlLogin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 90));

        btnLogeo.setBackground(new java.awt.Color(30, 30, 30));
        btnLogeo.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        btnLogeo.setForeground(new java.awt.Color(0, 204, 204));
        btnLogeo.setText("Logeo");
        pnlLogin.add(btnLogeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 100, 40));

        txtUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        pnlLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 300, 40));

        lblClave.setFont(new java.awt.Font("Rubik", 1, 24)); // NOI18N
        lblClave.setForeground(new java.awt.Color(0, 204, 204));
        lblClave.setText("Contraseña");
        pnlLogin.add(lblClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Rubik", 1, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 204, 204));
        lblUsuario.setText("Usuario");
        pnlLogin.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        pwdClave.setBackground(new java.awt.Color(0, 0, 0));
        pwdClave.setForeground(new java.awt.Color(0, 0, 0));
        pwdClave.setToolTipText("");
        pnlLogin.add(pwdClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 300, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLogeo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField pwdClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration                   
}
